apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- deployment.yaml
- oauth2-proxy-alpha-config.yaml
- oauth2-proxy-config.yaml

secretGenerator:
- name: oauth2-proxy
  type: Opaque
  envs:
  - secret_params.env

namespace: istio-system

generatorOptions:
  disableNameSuffixHash: true

images:
- name: quay.io/oauth2-proxy/oauth2-proxy
  newName: quay.io/oauth2-proxy/oauth2-proxy
  newTag: v7.4.0
