apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- service.yaml
- envoy-filter.yaml

namespace: istio-system

secretGenerator:
- name: authservice-client
  type: Opaque
  envs:
  - secret_params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: AUTHSERVICE_NAMESPACE
  objref:
    kind: Service
    name: authservice
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: AUTHSERVICE_SERVICE
  objref:
    kind: Service
    name: authservice
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
configurations:
- params.yaml
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: e236439
